### ISSUE TITLE
How to make it run  on MP4

### ISSUE THREAD

**Issue by Pavankunchala** [vladmandic/human-three-vrm#7]
This is a really awesome project I am just curious on how to make it run on mp4 rather than webcam

**Comment by vladmandic** [comment]
pretty trivial - library itself uses HTMLVideoElement as input, so only change needed is to assign `.src` to it instead of initializing webcam object on it.

See <https://github.com/vladmandic/human-three-vrm/blob/f2a85ad40a95e1a37fa10755d63e9059dc5f87ba/src/human-vrm.ts#L140>

So simply replace <https://github.com/vladmandic/human-three-vrm/blob/f2a85ad40a95e1a37fa10755d63e9059dc5f87ba/src/human-vrm.ts#L156> with `video.src = <your_uri_to_mp4>`
